### ISSUE TITLE
Task list 1.0

### ISSUE THREAD

**Issue by llJochemll** [BelgiumHell/Apollo.kunduz#1]
- [x] Supply system
  - [x] Supply drop
  - [x] Limited arsenal
  - [x] Crate merge
- [ ] Civilians
  - [x] Suicide bombers
  - [x] Normal behaviour
  - [ ] Conversation system (basic)
- [x] Taliban
  - [x] Defend hideouts
  - [x] IED's
  - [x] Patrolling
- [ ] HVT's
  - [ ] Commander behaviour (basic)
  - [x] lieutenant behaviour (basic)
  - [x] Field commander behaviour (basic)
  - [ ] Intel (basic)

**Comment by llJochemll** [comment]
Waiting for 1.56
